### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by f3l1x** [ondrs/Hi#5]
Hi!

Could you please create regular github releases, thus there's nothing at this moment.

https://componette.com/ondrs/hi/

**Comment by ondrs** [comment]
Done.
https://github.com/ondrs/Hi/releases

**Comment by f3l1x** [comment]
![selection_016](https://user-images.githubusercontent.com/538058/26928411-53d59f92-4c56-11e7-83c0-a0ff782d8d2e.png)

Much better thanks you. :-)
